# This will require each of these plugins automatically.
plugins:
   - jekyll-gist
   - jekyll-coffeescript
   - jekyll-assets
   - another-jekyll-plugin
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed

theme: jekyll-theme-hacker